import type { Metadata } from 'next';
import StyleProvider from '@/styles/provider';
import ThemeProvider from '@/styles/themeProvider';
import Globals from '@/styles/globals';
import Fonts from '@/styles/fonts';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import StoreProvider from '@/store/provider';
import { Modals } from '@/components/Modal';
import Header from '@/containers/Header';
import Loader from '@/containers/Loader';
import Footer from '@/containers/Footer';
import Notification from '@/providers/Notification';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Layout = async ({ children }: { children: React.ReactNode }) => {
  const locale = await getLocale();

  return (
    <Notification>
      <html className={Fonts.className} lang={locale}>
        <body>
          <StoreProvider>
            <StyleProvider>
              <ThemeProvider>
                <Globals />
                <NextIntlClientProvider>
                  <Header />
                  <Modals />
                  <Loader />
                  {children}
                  <Footer />
                </NextIntlClientProvider>
              </ThemeProvider>
            </StyleProvider>
          </StoreProvider>
        </body>
      </html>
    </Notification>
  );
};

export default Layout;
